name = "T4ATemplate"
uuid = "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
authors = ["tensor4all contributors"]
version = "0.1.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
PkgTemplates = "14b8a8f1-9102-5b29-a752-f990bacb7fe1"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
ArgParse = "1"
PkgTemplates = "0.7"
julia = "1.9"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Pkg", "Test"]

